# config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm
  mappings:
    product_images:  # This is the mapping name used in the entity
      uri_prefix: /uploads/products  # URL prefix for accessing the uploaded files
      upload_destination: '%kernel.project_dir%/public/uploads/products'  # Directory where files are stored
      namer: Vich\UploaderBundle\Naming\OrignameNamer  # Naming strategy for uploaded files
      delete_on_remove: true
      delete_on_update: true
